[core]

name: 测试小坦1
displayLocaleKey: tank
overrideAndReplace: tank
class: CustomUnitMetadata
price: 1
maxHp: 1000
maxShield: 500
shieldRegen: -0.1
energyMax: 30
energyRegen: -0.1
energyStartingPercentage: 0
mass: 3000
techLevel: 1
buildSpeed: 0.0020
#availableInDemo: true
radius: 11
displayRadius: 11
isBio: false
softCollisionOnAll: 0
@memory k:number
[graphics]
total_frames: 3
image: tank.png
image_wreak: tank_dead.png
image_turret: tank_turret.png
imageScale:0.8
turretImageScale:0.8
image_shadow: AUTO
shadowOffsetX:1
shadowOffsetY:1
animation_moving_start: 0
animation_moving_end: 2
animation_moving_speed: 1
dustEffect: true
[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false
turretSize: 20
turretTurnSpeed: 4
maxAttackRange: 75
shootDelay: 60
[turret_1]
x: 0
y: 0
projectile: 1
turnSpeedAcceleration: 1.0
shoot_sound:tank_firing
shoot_sound_vol:0.3
shoot_flame:small
shoot_light:#FFEECCCC
canShoot: true
recoilOffset: -2
[projectile_1]
directDamage: 60
life: 60
speed: 5
frame: 1
drawSize: 1
[action_1]
pos:1
text:充能
description:将护盾引擎过载
buildSpeed:3s
setUnitStats:maxShield=800,moveSpeed=3,shieldRegen=10,energy=30,shootDelayMultiplier=0.1
[hiddenAction_2]
autoTrigger:if self.isEnergyEmpty
resetUnitStats:true
[hiddenAction_3]
autoTriggerOnEvent:killedAnyUnit
setUnitMemory:k=(memory.k+1)
[hiddenAction_4]
autoTrigger:if memory.k>=3
setUnitMemory:k=(memory.k-3)
addEnergy:30
convertTo:测试小坦2
[hiddenAction_5]
autoTrigger:if self.isMoving
setUnitStats:shieldRegen=1
[hiddenAction_6]
autoTrigger:if not self.isMoving
resetUnitStats:true
[movement]
movementType: LAND
moveSpeed: 1.1
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.17
maxTurnSpeed: 4.1
turnAcceleration: 0.25
moveSlidingMode :false
moveIgnoringBody:false