[core]

radius:1
mass:1
maxHp:5000
name:炮塔模块
isUnselectable:true
price:5000
[hiddenAction_升级]
autoTrigger:if self.globalTeamTags(includes='升级T2') and not self.hasFlag(id=0)
setUnitStats:shootDamageMultiplier=1.1, maxAttackRange=250
addResources:setFlag=0
[hiddenAction_升级1]
autoTrigger:if self.globalTeamTags(includes='升级T3') and not self.hasFlag(id=1)
setUnitStats:shootDamageMultiplier=3,maxAttackRange=630
addResources:setFlag=1
[hiddenAction_升级2]
autoTrigger:if self.globalTeamTags(includes='升级T4') and not self.hasFlag(id=2)
setUnitStats:shootDamageMultiplier=8,maxAttackRange=780
addResources:setFlag=2
[hiddenAction_升级3]
autoTrigger:if self.globalTeamTags(includes='升级T5') and not self.hasFlag(id=3)
setUnitStats:shootDamageMultiplier=10,maxAttackRange=900
addResources:setFlag=3
[hiddenAction_升级4]
autoTrigger:if self.globalTeamTags(includes='升级T6') and not self.hasFlag(id=4)
setUnitStats:shootDamageMultiplier=15,maxAttackRange=1000
addResources:setFlag=4
[action_拆除]
text:拆除炮塔模块
textAddUnitName:${section.convertTo}
descriptionAddFromUnit:${section.convertTo}
descriptionAddUnitStats:${section.convertTo}
convertTo:武器模块
buildSpeed:3s
price:0
[graphics]
teamColorsOnTurret:true
image:武器模块.png
imageScale:0.75
image_shadow:AUTO
shadowOffsetX:1
shadowOffsetY:1
image_turret:炮塔模块.png
[attack]
canAttack:true
canAttackFlyingUnits:true
canAttackLandUnits:true
canAttackUnderwaterUnits:false
turretSize:30
turretTurnSpeed:2
maxAttackRange: 200
shootDelay:40
#turretMultiTargeting: true
[turret_0]
x:0
y:0
canShoot:false
[turret_1]
x:0
y:0
image:炮管模块.png
attachedTo:0
slave:true
projectile:1
idleDir:0
shoot_sound:large_gun_fire2
shoot_sound_vol:0.3
shoot_flame:large
shoot_light:#FFEECCCC
recoilOffset:-3
[projectile_1]
life:750
speed:6
largeHitEffect:true
frame:2
directDamage:250
drawSize:1
lightColor:#FF002D
lightSize:0.6
trailEffectRate:0.1
trailEffect:CUSTOM:尾焰
autoTargetingOnDeadTarget:true
[effect_尾焰]
image:SHARED:light_50.png
life:60
fadeOut:true
attachedToUnit:false
color:#FF002D
fadeInTime:2
scaleFrom:0.3
scaleTo:0.1
alpha:0.6
drawUnderUnits:false