[core]
name:外圈
maxHp:100
mass:100
price:50
radius:5
showInEditor:false
[graphics]
#图像节需要设置主体图像
image:内.pug
scaleImagesTo:0.5
[attack]
canAttack:false
[movement]
movementType:NONE
[arm_1]
x:0
y:0
image_end:外圈.png
spinRate:-0.2