[core]
mass:9999999
price:640000
buildSpeed:30s
name:猎雀
displayDescription:T3级\n亮色激光伤害较低，但能穿透护盾与护甲造成伤害\n暗色激光伤害较高，并且无视大量装甲，但对护盾效果极差\n设计师：蜂后
maxHp:35000
selfRegenRate:3
radius:100
autoTriggerCooldownTime:0.1s
energyMax:20
energyRegen:0.02
energyNeedsToRechargeToFull:true
softCollisionOnAll:24
tags:猎雀
[graphics]
#图像节需要设置主体图像
image:烈.pug
scaleImagesTo:115
image_shadow:AUTO
shadowOffsetX:5
shadowOffsetY:5
[attack]
canAttack:true
canAttackFlyingUnits:true
canAttackUnderwaterUnits:false
canAttackLandUnits:true
shootDelay:40
turretTurnSpeed:1
[turret_白激光]
x:0
y:52.5
canAttack:false
idleSpin:1
image:白环.pug
limitingRange:0
[turret_黑激光]
x:0
y:-132.5
canAttack:false
idleSpin:-1
image:黑环.pug
limitingRange:0
[turret_开白激光]
x:0
y:52.5
canAttack:true
limitingRange:750
projectile:白
delay:1
[turret_开黑激光]
x:0
y:-132.5
canAttack:true
limitingRange:750
projectile:黑
delay:1
[projectile_白]
life:10
directDamage:50
frame:1
laserEffect:true
largeHitEffect:true
speed:1
armourIgnoreAmount:500
shieldDamageMultiplier:1
shieldDefectionMultiplier:0
buildingDamageMultiplier:1
color:#9EFFFF
instantReuseLast:true
instant:true
sweepSpeed:50
sweepOffset:10
[projectile_黑]
life:10
directDamage:125
frame:1
laserEffect:true
largeHitEffect:true
speed:1
armourIgnoreAmount:500
shieldDamageMultiplier:0.1
buildingDamageMultiplier:1
color:#5F9F9F
instantReuseLast:true
instant:true
sweepSpeed:50
sweepOffset:10
[movement]
movementType:AIR
moveSpeed:0.5
moveAccelerationSpeed:0.06
moveDecelerationSpeed:0.06
maxTurnSpeed:0.7
turnAcceleration:0.03
moveSlidingMode:false
moveIgnoringBody:false
slowDeathFall:true
[attachment_内圈]
x:0
y:52.5
isUnselectable:true
canBeAttackedAndDamaged:false
addTransportedUnits:true
setDrawLayerOnBottom:true
canAttack:true
lockRotation:true
idleDir:0
onCreateSpawnUnitOf:内圈
[attachment_外圈]
x:0
y:-132.5
isUnselectable:true
canBeAttackedAndDamaged:false
addTransportedUnits:true
setDrawLayerOnBottom:true
canAttack:true
lockRotation:true
idleDir:0
onCreateSpawnUnitOf:外圈
[attachment_外圈2]
x:0
y:-132.5
isUnselectable:true
canBeAttackedAndDamaged:false
addTransportedUnits:true
setDrawLayerOnBottom:true
canAttack:true
lockRotation:true
idleDir:0
onCreateSpawnUnitOf:内小圈
[hiddenAction_触发]
autoTrigger:if self.hp(greaterThan=1)
spawnEffects:custom:法球
[effect_法球]
image:球.png
alpha:1
fadeOut:true
life:150
attachedToUnit:true
drawUnderUnits:false
xOffsetRelative:0
yOffsetRelative:-206
atmospheric:true
priority:critical
scaleFrom:2
scaleTo:0.1
[ai]
buildPriority:0.97
noneInBaseExtraPriority:1