[core]

radius:1
mass:1
maxHp:5000
name:激光拦截模块(右)
isUnselectable:true
price:3000
energyMax:1
energyRegen:0.0003
[action_拆除]
text:拆除激光拦截模块
textAddUnitName:${section.convertTo}
descriptionAddFromUnit:${section.convertTo}
descriptionAddUnitStats:${section.convertTo}
convertTo:特种模块(右)
buildSpeed:3s
price:0
[attack]
canAttack:false
canAttackFlyingUnits:false
canAttackLandUnits:true
canAttackUnderwaterUnits:false
turretSize:30
turretTurnSpeed:2
#maxAttackRange: 200
shootDelay:85
[turret_laserDefence]
x:0
y:0
canShoot:false
laserDefenceEnergyUse:0.05
limitingRange:400
size:1
[graphics]
image:防御模块.png
image_turret:激光拦截模块.png
imageScale:0.75
image_shadow:AUTO
shadowOffsetX:1
shadowOffsetY:1
drawLayer:bottom