[core]

tags:狐,厄之抵抗,拾月
name:狐
maxHp:10
mass:50
price:999999999
radius:10
displayDescription:不要888不要999只要9.99e，小狐带回家
isBio:true
isBuilder:true
buildSpeed:300s
softCollisionOnAll:9
showActionsWithMixedSelectionIfOtherUnitsHaveTag:狐
fogOfWarSightRange:99999
soundOnAttackOrder:狐攻击.ogg
soundOnNewSelection:狐出发.ogg,狐出发2.ogg
canOnlyBeAttackedByUnitsWithTags:无敌状态
disableDeathOnZeroHp:true
[graphics]
#图像节需要设置主体图像
imageScale:0.9
image:狐.png
scaleImagesTo:14.5
image_shadow:AUTO
shadowOffsetX:2
shadowOffsetY:2
showHealthBar:false
showEnergyBar:false
total_frames:2
animation_attack_start:0
animation_attack_end:1
animation_attack_speed:5
lock_body_rotation_with_main_turret:true
[attack]
canAttack:true
canAttackFlyingUnits:true
canAttackLandUnits:true
canAttackUnderwaterUnits:false
maxAttackRange:300
shootDelay:15
[turret_113]
y:0
x:0
barrelX:2
barrelY:20
shoot_light:#FFD700
recoilOffset:-0.5
shoot_sound:开火.ogg
[projectile_SOPPP]
life:200
areaDamage:500000
areaRadius:100
armourIgnoreAmount:100000
targetGroundSpread:0.05
image:子弹.png
drawSize:0.4
speed:15
deflectionPower:-1
explodeEffect:small
[resource_ER]
displayName:物质归一
hidden:false
[action_物质抵抗]
isVisible:false
isLocked:true
isActive:false
buildSpeed:0s
price:0
autoTrigger:true
text:物质抵抗
description:抵抗物质归一
addResources:ER=-100
[action_1]
convertTo:狐（休闲）
price:0
text:休闲状态
buildSpeed:0.1
pos:0.2
alwaysSinglePress:true
iconImage:狐休闲.png
playSoundAtUnit:模式更换.ogg
[hiddenAction_失败]
isVisible:false
ai_isDisabled:true
convertTo:虚无
autoTrigger:if numberOfUnitsInTeam(withTag='狐',greaterThan=1)
[movement]
movementType:HOVER
moveSpeed:0.69
maxTurnSpeed:4
reverseSpeedPercentage:0.3
[action_水]
autoTrigger:if self.isOverwater()
convertTo:狐（水上）
isVisible:false
[ai]
disableUse:true