[core]

tags:狐,厄之抵抗,拾月
name:狐（死亡）
maxHp:0
mass:50
price:0
radius:10
isBio:true
showInEditor:false
[graphics]
#图像节需要设置主体图像
imageScale:0.9
image:狐.png
image_wreak:狐尸体.png
scaleImagesTo:14.5
image_shadow:AUTO
shadowOffsetX:2
shadowOffsetY:2
showHealthBar:false
showEnergyBar:false
total_frames:2
animation_attack_start:0
animation_attack_end:1
animation_attack_speed:5
lock_body_rotation_with_main_turret:true
[attack]
canAttack:false
[movement]
movementType:HOVER
moveSpeed:0
maxTurnSpeed:0
reverseSpeedPercentage:0