[core]

tags:狐,厄之抵抗,拾月
name:狐（水上）
maxHp:10
mass:50
price:0
radius:10
displayDescription:不要888不要999只要9.99e，小狐带回家
isBio:true
isBuilder:true
buildSpeed:13s
softCollisionOnAll:9
showInEditor:false
showActionsWithMixedSelectionIfOtherUnitsHaveTag:狐
fogOfWarSightRange:99999
soundOnAttackOrder:狐攻击.ogg
soundOnNewSelection:狐出发.ogg,狐出发2.ogg
canOnlyBeAttackedByUnitsWithTags:无敌状态
disableDeathOnZeroHp:true
[graphics]
#图像节需要设置主体图像
imageScale:0.9
image:狐.png
scaleImagesTo:14.5
image_shadow:AUTO
shadowOffsetX:2
shadowOffsetY:2
showHealthBar:false
showEnergyBar:false
total_frames:2
animation_attack_start:0
animation_attack_end:1
animation_attack_speed:5
lock_body_rotation_with_main_turret:true
[attack]
canAttack:true
canAttackFlyingUnits:true
canAttackLandUnits:true
canAttackUnderwaterUnits:false
maxAttackRange:300
shootDelay:15
[turret_113]
y:0
x:0
barrelX:2
barrelY:20
shoot_light:#FFD700
recoilOffset:-0.5
shoot_sound:开火.ogg
[projectile_SOPPP]
life:200
areaDamage:500000
areaRadius:100
armourIgnoreAmount:100000
targetGroundSpread:0.2
image:子弹.png
drawSize:0.4
speed:15
deflectionPower:-1
explodeEffect:small
[action_传送1]
isVisible:false
whenBuilding_cannotMove:true
displayType:action
buildSpeed:0.01s
pos:1
spawnEffects:CUSTOM:传送
[action_传送]
fireTurretXAtGround:传送1
fireTurretXAtGround_withProjectile:传送1
fireTurretXAtGround_onlyOverPassableTileOf:HOVER
whenBuilding_cannotMove:true
whenBuilding_triggerAction:传送1
text:传送
displayType:action
buildSpeed:0.45s
pos:0.1
onlyOneUnitAtATime:false
allowMultipleInQueue:false
addActionCooldownTime:0.01s
[effect_传送]
life:9999
fadeInTime:0
fadeOut:false
attachedToUnit:false
image:传送.png
total_frames:5
animateFrameStart:0
animateFrameStartRandomAdd:0
animateFrameEnd:4
animateFramePingPong:true
animateFrameSpeed:0.3
[turret_传送1]
x:0
y:0
canShoot:false
invisible:true
size:1
turnSpeed:40
limitingRange:9999
[projectile_传送1]
teleportSource:true
directDamage:0
life:99999
instant:true
targetGround:true
invisible:true
deflectionPower:-1
shouldRevealFog:true
[hiddenAction_失败]
isVisible:false
ai_isDisabled:true
convertTo:虚无
autoTrigger:if numberOfUnitsInTeam(withTag='狐',greaterThan=1)
[movement]
movementType:HOVER
moveSpeed:0.69
maxTurnSpeed:4
reverseSpeedPercentage:0.3
[action_水]
autoTrigger:if not self.isOverwater()
convertTo:狐
isVisible:false