[core]

tags:狐,厄之抵抗,拾月
name:狐（休闲）
displayText:狐（休闲）
maxHp:10
mass:50
price:0
radius:10
displayDescription:小狐休息ing...
isBio:true
isBuilder:true
showInEditor:false
showActionsWithMixedSelectionIfOtherUnitsHaveTag:狐
fogOfWarSightRange:99999
softCollisionOnAll:9
soundOnAttackOrder:狐攻击.ogg
soundOnNewSelection:狐出发.ogg,狐出发2.ogg
canOnlyBeAttackedByUnitsWithTags:无敌状态
disableDeathOnZeroHp:true
[attack]
canAttack:false
[action_1]
convertTo:狐
price:0
text:战斗状态
buildSpeed:0.1
pos:0.1
alwaysSinglePress:true
iconImage:狐战斗.png
playSoundAtUnit:模式更换.ogg
[graphics]
#图像节需要设置主体图像
image:狐休闲.png
scaleImagesTo:56
showHealthBar:false
imageScale:0.9
showEnergyBar:false
image_shadow:AUTO
shadowOffsetX:2
shadowOffsetY:2
[action_传送1]
isVisible:false
whenBuilding_cannotMove:true
displayType:action
buildSpeed:0.01s
pos:1
spawnEffects:CUSTOM:传送
[action_传送]
fireTurretXAtGround:传送1
fireTurretXAtGround_withProjectile:传送1
fireTurretXAtGround_onlyOverPassableTileOf:HOVER
whenBuilding_cannotMove:true
whenBuilding_triggerAction:传送1
text:传送
displayType:action
buildSpeed:0.45s
pos:0.1
onlyOneUnitAtATime:false
allowMultipleInQueue:false
addActionCooldownTime:0.01s
[effect_传送]
life:9999
fadeInTime:0
fadeOut:false
attachedToUnit:false
image:传送.png
total_frames:5
animateFrameStart:0
animateFrameStartRandomAdd:0
animateFrameEnd:4
animateFramePingPong:true
animateFrameSpeed:0.3
[action_2]
convertTo:狐（死亡）
pos:1
price:0
text:自杀
buildSpeed:1s
[action_3]
spawnUnits:V.Z--克洛诺斯*9999999
pos:2
price:0
text:结束游戏
playSoundToPlayerOnQueue:结束装填.ogg
buildSpeed:3s
[turret_传送1]
x:0
y:0
canShoot:false
invisible:true
size:1
turnSpeed:40
limitingRange:9999
[projectile_传送1]
teleportSource:true
directDamage:0
life:1
instant:true
targetGround:true
invisible:true
deflectionPower:-1
shouldRevealFog:true
[hiddenAction_失败]
isVisible:false
ai_isDisabled:true
convertTo:虚无
autoTrigger:if numberOfUnitsInTeam(withTag='狐',greaterThan=1)
[movement]
movementType:HOVER
moveSpeed:1.5
maxTurnSpeed:4
reverseSpeedPercentage:0.3